server:
  port: 8181
spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    database: H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    sql-script-encoding: UTF-8
